apiVersion: kobe.semagrow.org/v1alpha1
kind: DatasetTemplate
metadata:
  name: strabontemplate
spec:
  initContainers:
    - name: initcontainer0
      image: semagrow/url-downloader:v1
    - name: initcontainer1
      image: semagrow/strabon-init:feat-pbbench
  containers:
    - name: maincontainer
      image: semagrow/strabon-main:feat-pbbench0
      ports:
        - containerPort: 8080
  port: 8080
  path: /Strabon/Query
  initPolicy: ForceInit
